version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5442:5432"  # Проброс порта явно
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always

  init_db:
    build: .
    container_name: init_db
    command: python database/models.py
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      PYTHONPATH: /app
    restart: "no"

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A celery_worker.worker.celery_app worker --loglevel=info
    volumes:
      - .:/app
    environment:
      PYTHONPATH: /app
    depends_on:
      - redis
      - postgres
    restart: always

  fastapi_app:
    build: .
    container_name: fastapi_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      PYTHONPATH: /app
    depends_on:
      - postgres
      - redis
    restart: always

volumes:
  pgdata:
